FROM node:18

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy the app source
COPY . .

# Expose Vite dev port
EXPOSE 5173

# Start dev server
CMD ["npm", "run", "dev", "--", "--host"]
